name       : vim
version    : 8.0.0987
release    : 79
source     :
    - https://github.com/vim/vim/archive/v8.0.0987.tar.gz : 2c104dd55dec46a37f9a1e4bc886c2720f10431f97248517fde04fbb6d355b59
homepage   : http://www.vim.org/
license    : GPL-2.0
component  : editor
summary    : Vi IMproved, an advanced text editor
description: |
    Vim, which stands for Vi IMproved, is an open-source, multiplatform text editor extended from vi. It was first released by Bram Moolenaar in 1991. Since then, numerous features have been added to Vim, many of which are helpful in editing program source code.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(lua-5.1)
    - pkgconfig(ruby-2.2)
    - pkgconfig(tcl)
    - pkgconfig(python3)
    - pkgconfig(x11)
    - pkgconfig(xpm)
    - pkgconfig(xt)
    - gpm-devel
setup      : |
    %configure \
        --disable-netbeans \
        --disable-perlinterp \
        --enable-gui=gtk3 \
        --enable-fail-if-missing \
        --enable-luainterp \
        --enable-multibyte \
        --enable-pythoninterp \
        --enable-python3interp \
        --enable-rubyinterp \
        --enable-luainterp \
        --enable-tclinterp \
        --with-compiledby="Solus" \
        --with-features=huge \
        --with-lua-prefix=/usr \
        --with-modified-by="Solus"
build      : |
    %make
install    : |
    %make_install -j1
    install -dm644 $installdir/etc/vim/
    install -Dm644 $pkgfiles/gvim.desktop $installdir/usr/share/applications/gvim.desktop
    install -Dm644 $workdir/runtime/vim48x48.png $installdir/usr/share/pixmaps/gvim.png
    install -Dm644 $pkgfiles/vimrc $installdir/usr/share/vim/vimrc
    install -Dm644 $pkgfiles/vimrc.tiny $installdir/usr/share/vim/vimrc.tiny
    ln -s /usr/bin/vim $installdir/usr/bin/vi
    ln -s /usr/share/vim/vimrc $installdir/etc/vim/vimrc
    ln -s /usr/share/vim/vimrc.tiny $installdir/etc/vim/vimrc.tiny
